backend:
  name: git-gateway
  branch: develop
publish_mode: editorial_workflow
media_folder: static/assets

collections:
  - name: livre
    label: Livre
    folder: data/books
    create: true
    fields:
      - { name: date, label: Dates de parution, widget: date }
      - { name: title, label: Titre }
      - { name: description, label: Description }
      - { name: cover, label: Couverture }
      - { name: link, label: Lien magasin }
      - { name: video, label: Vidéo }
  - name: article
    label: Article
    folder: data/articles
    create: true
    fields:
      - { name: date, label: Date de publication, widget: date }
      - { name: title, label: Titre }
      - { name: description, label: Description }
      - { name: body, label: Texte }
      - { name: author, label: Auteur }
      - { name: category, label: Catégorie }
