backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: "livre"
    label: "Livres"
    label_singular: "Livre"
    folder: "data/books"
    slug: "{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { name: date, label: Dates de parution, widget: date, required: true }
      - { name: title, label: Titre, widget: "string", required: true }
      - { name: body, label: Description, widget: "markdown", required: true }
      - { name: cover, label: Couverture, required: true }
      - { name: link, label: Lien magasin }
      - { name: video, label: Vidéo }

  - name: "article"
    label: "Articles"
    label_singular: "Article"
    folder: "data/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: date, label: Date de publication, widget: date, required: true }
      - { name: title, label: Titre, widget: "string", required: true }
      - { name: description, label: Description, widget: "text", required: true }
      - { name: body, label: Texte, widget: "markdown", required: true }
      - { name: author, label: Auteur, widget: "string" }
      - { name: category, label: Catégorie }
      - { name: thumbnail, label: Image de présentation, widget: image }
